---
extends: default

rules:
  line-length:
    max: 120
  comments:
    require-starting-space: true
    min-spaces-from-content: 2
    level: error
  comments-indentation:
    level: error
  document-start:
    level: error
  empty-values: enable
  float-values: enable
  octal-values: enable
  quoted-strings:
    quote-type: single
    required: only-when-needed
  truthy:
    level: warning
