CREATE TABLE student (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  first_name  TEXT CHECK (LENGTH(first_name) <= 100) NOT NULL,
  last_name   TEXT CHECK (LENGTH(last_name) <= 100),
  profile_pic TEXT CHECK (LENGTH(profile_pic) <= 250),
  section_id  SMALLINT NOT NULL REFERENCES section (id)
);
